### ISSUE TITLE
The question about preprocessing dataset

### ISSUE THREAD

**Issue by hanxunyu** [Chat-3D/Chat-3D-v2#22]
Thanks for your great work! But when I try to reproduce it, I encountered the following two problems:
1. After running your code "extract_3dfeat.py", I think the result I got are discrete features of every object in each scene of ScanNet dataset. But I didn't return the file "scannet_ulip2_feats.pt", which I guess is a collection of features of all the objects in all scenes? Is that right and how can I get this file on my own?
![image](https://github.com/Chat-3D/Chat-3D-v2/assets/64463353/e873fc43-5c3c-4e6b-948c-45206b37aa33)
2. Could you please release the code about how to get each processed annotation provided in your [GoogleDrive](https://drive.google.com/drive/folders/19wOjXYjca6w3JRVzbbFMgwiQj6kd6MXQ?usp=drive_link) when you have chance (would be best if there was an explanation of the function of each subfile)?
![image](https://github.com/Chat-3D/Chat-3D-v2/assets/64463353/b98f7464-800f-4940-8940-16437ef604f7)

Thanks again for this excellent work. And I would appreciate a lot for your reply.

**Comment by ZzZZCHS** [comment]
1. Yes, you are right. `scannet_ulip2_feats.pt` is a collection of all the objects' features, which is dict with keys in the format of `{scene_id}_{obj_id:02}`. Since you've generated all the seperate features of each object, you can write a simple code to walk through all the files under the output folder and collect them into one dict.

2. Thanks for your suggestion. The currently released codes and annotations are a bit messy. We are refining our code recently and will re-organize these annotations and instructions later.

**Comment by hanxunyu** [comment]
Thanks for your quick reply. Cool! Looking forward to your amazing refined instructions~

**Comment by ZzZZCHS** [comment]
Hi @hanxunyu, we've released the instructions for preprocessing. Welcome to check it and raise any further questions~
