### ISSUE TITLE
Point cloud data feature

### ISSUE THREAD

**Issue by KimWu1994** [Chat-3D/Chat-3D-v2#28]
Hello, in `preprocess/extract_3dfeat.py` and feature file 'data/annotations/scannet_pointgroup_uni3d_feats.pt'. 
For example, one of the data is  'scene0000_00_02'. 
I think the first '0000' regards the scene number. But what does the second '_00_' regard? What does the third '02' regard?

**Comment by ZzZZCHS** [comment]
For 'scene0000_00_02', 'scene0000_00' is the scene id, '02' is the object id.

**Comment by KimWu1994** [comment]
How do I know which object the object id corresponds to?

**Comment by ZzZZCHS** [comment]
For 3D instance segmentation models like PointGroup and Mask3D, their predicted result for each scene is a list of instances with their ID, predicted mask, and confidence score. We directly use the IDs in the predicted results. Since the predicted results (especially the masks) are too large to be released, I recommend you referring to their repos ([PointGroup](https://github.com/dvlab-research/PointGroup), [Mask3D](https://github.com/JonasSchult/Mask3D)) to run the instance segmentation with their pretrained weights. We postprocess the predicted results into sets of (ID, bbox, class name), which can be further visualized in the 3D scene. We will release the processing scripts within this week.

**Comment by KimWu1994** [comment]
Thanks so much !!! 
I get it.
